# Generated by Django 3.2.7 on 2024-03-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_ake_kws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='tag',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
