# Generated by Django 3.2.7 on 2024-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_ake_kws', '0002_auto_20240401_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='fileType',
            field=models.CharField(default='sf', max_length=225),
            preserve_default=False,
        ),
    ]
