# Generated by Django 3.2.7 on 2024-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_ake_kws', '0003_encryptedfile_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(default='sdf', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
